### ISSUE TITLE
Skip to navigation button

### ISSUE THREAD

**Issue by jeroenvdmeer** [nickwaelkens/ra-language-dutch#13]
Version 3.12.0 of React-Admin added a button to skip navigation. This also included a new property in the translation methods: ra.navigation.skip_nav. This property is missing in the latest version of ra-language-dutch. Could this property be added, for instance with the value "Doorgaan naar artikel"?

[Source: commit d5d4a...](https://github.com/marmelab/react-admin/commit/d5d4a47e3f713cc1335a7032ca7ff17f27db078a#diff-d55e636245f2994de4a9a74002cca1fec0a6a2e68d1805a5439a0c885f37263b)

**Comment by nickwaelkens** [comment]
Hey @jeroenvdmeer, thanks for flagging! 
Fixed in https://github.com/nickwaelkens/ra-language-dutch/pull/14, published to [npm](https://www.npmjs.com/package/ra-language-dutch) as well.
