### ISSUE TITLE
3.16.3 is broken

### ISSUE THREAD

**Issue by jpstijn** [nickwaelkens/ra-language-dutch#16]
### Current Behavior
In 'ra-core' 3.16.5 the type of TranslationMessages is updated. Because the types are not added in index.ts the build of every application fails with version 3.16.3 of ra-language-dutch

### Expected Behavior
Types should match.

**Comment by jpstijn** [comment]
Version 3.16.3 seems broken `'TranslationMessages'.
    The types of 'ra.action' are incompatible between these types.`

**Comment by nickwaelkens** [comment]
@jpstijn Thanks for flagging! I've just published [v3.17.2 to npm](https://www.npmjs.com/package/ra-language-dutch) which should fix this!
